### ISSUE TITLE
Flag raised for cloudhub deployments

### ISSUE THREAD

**Issue by juanc-mulesoft** [UFGInsurance/mulint#56]
Warning when checking projects where maven vars were removed, we are not using maven deployments anymore.
C:\repo\mulesoft-apis>mulint "C:\repo\mulesoft-apis\Experience APIs\policyholder-admin-web-exp-api"
[warning]  Domain project used (deploying to CloudHub)

1 problems found (0 errors, 1 warnings)

This is the line of code that checks if the deployment is onprem:
`let isOnPrem = properties.get("deployment.type") === "arm";`

We can remove this validation since we're not using maven deployments and cloudhub.

**Comment by TrueWill** [comment]
Thanks for opening this, @juanc-mulesoft ! I will look into it.

**Comment by TrueWill** [comment]
@juanc-mulesoft Running mulint on policyholder-admin-web-exp-api I get "No problems found". Is there a branch you're working on?

Am I correct in assuming that you're removing the entire property `<deployment.type>arm</deployment.type>` since you're not using the Mule Maven Plugin?

If possible I want to allow mulint to work for other companies who may still be using the Maven plugin and/or CloudHub, as it is open source. UFG's needs come first though.

**Comment by juanc-mulesoft** [comment]
Yes, there is a branch: security/ph-admin-web-exp-api
Then, we need other way to know if the deployment is for cloudhub other than deployment variables.
